packages:
  - "packages/*"
  - "apps"
  - "libs/*"
  - "components/*"
  - "!**/tests/*" # Exclude the 'tests' folder from being considered a package
  - "projects/*"

link-workspace-packages: true # Automatically link workspace packages (optional)
